site_name: CrystalExpressLite 文檔 - iOS
theme: readthedocs
site_favicon: favicon.ico
extra_css:
- css/custom.css
pages:
- 首頁: index.md
- 整合導覽:
  - '安裝設定與基本要求': 'docs/setup.md'
  - '廣告整合':
    - '初始化': 'docs/sdk-init.md'
    - '原生廣告': 'docs/native-ad.md'
- 廣告預覽: 'docs/ad-preview.md'
- 測試模式: 'docs/test-mode.md'
- 上線前檢查: 'docs/before-go-production.md'
- API 參考: 'docs/api-reference.md'
- 疑難排解: 'docs/trouble-shooting.md'
